apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: {{.Values.nombreNs}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{.Values.nombreApp}}
  template:
    metadata:
      labels:
        app: {{.Values.nombreApp}}
    spec:
      containers:
        - name: saludo-quarkus
          image: "{{.Values.imagen.usuario}}/{{.Values.imagen.nombre}}:{{.Values.imagen.tag}}"
          ports:
            - containerPort: {{.Values.puertoApp}}
