apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: {{.Values.nombreNs}}
spec:
  type: {{.Values.tipoSvc}}
  selector:
    app: {{.Values.nombreApp}}
  ports:
    - protocol: TCP
      port: {{.Values.puertoApp}}
      targetPort: {{.Values.puertoApp}}